import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { SelectedRolesProvider } from '@/context/SelectedRoles/SelectedRolesProvider'
import './globals.css'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Event Calendar for Tabletop Game Events',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
            <body>
                <SelectedRolesProvider>{children}</SelectedRolesProvider>
            </body>
        </html>
    )
}
